name: Build and Release APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java (required for Android builds)
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    # Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'

    # Create .env file
    - name: Create .env file
      run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

    # Create gemini_service_account.json file
    - name: Create gemini_service_account.json
      run: echo "${{ secrets.GEMINI_SERVICE_ACCOUNT }}" > lib/core/services/gemini_service_account.json

    # Clean Flutter Cache
    - name: Clean Flutter Cache
      run: flutter clean

    - name: Install dependencies
      run: flutter pub get

    # Build the APK
    - name: Build APK
      run: flutter build apk --release --split-per-abi

    # Upload the APKs as artifacts
    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apks
        path: build/app/outputs/flutter-apk/*.apk

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Download the APK artifact
    - name: Download APK artifact
      uses: actions/download-artifact@v4
      with:
        name: app-release-apks

    # Create a release and upload the APK
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ github.run_number }}
        name: Release v${{ github.run_number }}