name: Build and Release APK

on:
  push:
    branches:
      - main # Trigger the workflow on commits to the main branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java (required for Android builds)
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    # Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    # Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Build the APK
    - name: Build APK
      run: flutter build apk --release --split-per-abi

    # Upload the APKs as artifacts
    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apks
        path: build/app/outputs/flutter-apk/*.apk

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Download the APK artifact
    - name: Download APK artifact
      uses: actions/download-artifact@v3
      with:
        name: app-release.apk

    # Create a release and upload the APK
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: app-release.apk
        token: ${{ secrets.TOKEN }}
        tag: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false